-- Aveniq SaaS V1 standalone database.
-- Run only in a NEW, empty Supabase project created for Aveniq.

create extension if not exists pgcrypto;
create extension if not exists unaccent;

create table public.restaurants (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  slug text not null unique,
  restaurant_type text not null default '',
  logo_url text not null default '',
  address text not null default '',
  phone text not null default '',
  timezone text not null default 'Australia/Sydney',
  status text not null default 'onboarding' check (status in ('onboarding','active','suspended','inactive')),
  subtitle text not null default 'QR table ordering',
  tax_id text not null default '',
  tax_rate numeric(5,2) not null default 10 check (tax_rate between 0 and 30),
  is_open boolean not null default true,
  is_active boolean not null default true,
  theme_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.restaurant_staff (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'cashier' check (role in ('owner','manager','kitchen','cashier')),
  created_at timestamptz not null default now(),
  unique (restaurant_id, user_id)
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (restaurant_id, name)
);

create table public.tables (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  table_number integer,
  table_name text not null,
  qr_code_url text not null default '',
  local_id text not null,
  name text not null,
  table_token text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, local_id),
  unique (restaurant_id, table_number)
);

create table public.menu_items (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  image_url text not null default '',
  is_available boolean not null default true,
  sort_order integer not null default 0,
  local_id text not null,
  category text not null,
  tags jsonb not null default '[]'::jsonb,
  photo_url text not null default '',
  option_template text not null default 'none',
  sold_out boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, local_id)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete restrict,
  table_id uuid not null references public.tables(id) on delete restrict,
  order_number bigint generated by default as identity,
  customer_name text not null default '',
  status text not null default 'new' check (status in ('new','preparing','ready','completed','cancelled')),
  subtotal numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  local_id text,
  public_token uuid not null default gen_random_uuid() unique,
  note text not null default '',
  tax numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  served_at timestamptz,
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete restrict,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  item_name text not null,
  quantity integer not null check (quantity between 1 and 99),
  price numeric(10,2) not null check (price >= 0),
  notes text not null default '',
  name_snapshot text not null,
  base_price numeric(10,2) not null default 0,
  unit_price numeric(10,2) not null default 0,
  options jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index restaurant_staff_user_idx on public.restaurant_staff(user_id, restaurant_id);
create index categories_restaurant_sort_idx on public.categories(restaurant_id, sort_order);
create index tables_restaurant_active_idx on public.tables(restaurant_id, is_active, sort_order);
create index menu_items_restaurant_category_idx on public.menu_items(restaurant_id, category_id, sort_order);
create index orders_restaurant_status_created_idx on public.orders(restaurant_id, status, created_at desc);
create unique index orders_restaurant_local_unique on public.orders(restaurant_id, local_id) where local_id is not null;
create index order_items_restaurant_order_idx on public.order_items(restaurant_id, order_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger restaurants_updated_at before update on public.restaurants
for each row execute function public.set_updated_at();
create trigger tables_updated_at before update on public.tables
for each row execute function public.set_updated_at();
create trigger menu_items_updated_at before update on public.menu_items
for each row execute function public.set_updated_at();
create trigger orders_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.is_restaurant_staff(target_restaurant uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.restaurant_staff
    where restaurant_id = target_restaurant and user_id = auth.uid());
$$;

create or replace function public.has_restaurant_role(target_restaurant uuid, allowed_roles text[])
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.restaurant_staff
    where restaurant_id = target_restaurant and user_id = auth.uid() and role = any(allowed_roles));
$$;

revoke all on function public.is_restaurant_staff(uuid) from public;
revoke all on function public.has_restaurant_role(uuid,text[]) from public;
grant execute on function public.is_restaurant_staff(uuid), public.has_restaurant_role(uuid,text[]) to authenticated;

alter table public.restaurants enable row level security;
alter table public.restaurant_staff enable row level security;
alter table public.categories enable row level security;
alter table public.tables enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "public read active restaurants" on public.restaurants for select to anon, authenticated
using (status = 'active' and is_active);
create policy "staff read own restaurants" on public.restaurants for select to authenticated
using (public.is_restaurant_staff(id));
create policy "owners manage restaurant" on public.restaurants for update to authenticated
using (public.has_restaurant_role(id,array['owner','manager']))
with check (public.has_restaurant_role(id,array['owner','manager']));

create policy "staff read own memberships" on public.restaurant_staff for select to authenticated
using (user_id = auth.uid());
create policy "owners manage staff" on public.restaurant_staff for all to authenticated
using (public.has_restaurant_role(restaurant_id,array['owner']))
with check (public.has_restaurant_role(restaurant_id,array['owner']));

create policy "staff read categories" on public.categories for select to authenticated
using (public.is_restaurant_staff(restaurant_id));
create policy "owners manage categories" on public.categories for all to authenticated
using (public.has_restaurant_role(restaurant_id,array['owner','manager']))
with check (public.has_restaurant_role(restaurant_id,array['owner','manager']));

create policy "staff read tables" on public.tables for select to authenticated
using (public.is_restaurant_staff(restaurant_id));
create policy "owners manage tables" on public.tables for all to authenticated
using (public.has_restaurant_role(restaurant_id,array['owner','manager']))
with check (public.has_restaurant_role(restaurant_id,array['owner','manager']));

create policy "staff read menu" on public.menu_items for select to authenticated
using (public.is_restaurant_staff(restaurant_id));
create policy "owners manage menu" on public.menu_items for all to authenticated
using (public.has_restaurant_role(restaurant_id,array['owner','manager']))
with check (public.has_restaurant_role(restaurant_id,array['owner','manager']));

create policy "staff read orders" on public.orders for select to authenticated
using (public.is_restaurant_staff(restaurant_id));
create policy "staff update orders" on public.orders for update to authenticated
using (public.is_restaurant_staff(restaurant_id))
with check (public.is_restaurant_staff(restaurant_id));

create policy "staff read order items" on public.order_items for select to authenticated
using (public.is_restaurant_staff(restaurant_id));

create or replace function public.create_restaurant_for_owner(
  p_name text, p_restaurant_type text, p_phone text, p_address text,
  p_logo_url text default '', p_timezone text default 'Australia/Sydney'
) returns jsonb language plpgsql security definer set search_path = public as $$
declare target_id uuid; target_slug text; base_slug text;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if exists(select 1 from public.restaurant_staff where user_id = auth.uid() and role = 'owner') then
    raise exception 'OWNER_RESTAURANT_ALREADY_EXISTS';
  end if;
  if length(trim(coalesce(p_name,''))) < 2 then raise exception 'INVALID_RESTAURANT_NAME'; end if;
  base_slug := trim(both '-' from regexp_replace(lower(unaccent(p_name)),'[^a-z0-9]+','-','g'));
  if base_slug = '' then base_slug := 'restaurant'; end if;
  target_slug := base_slug;
  while exists(select 1 from public.restaurants where slug = target_slug) loop
    target_slug := base_slug || '-' || substr(replace(gen_random_uuid()::text,'-',''),1,5);
  end loop;
  insert into public.restaurants(owner_user_id,name,slug,restaurant_type,phone,address,logo_url,timezone,status)
  values(auth.uid(),trim(p_name),target_slug,trim(coalesce(p_restaurant_type,'')),trim(coalesce(p_phone,'')),
    trim(coalesce(p_address,'')),trim(coalesce(p_logo_url,'')),coalesce(nullif(trim(p_timezone),''),'Australia/Sydney'),'onboarding')
  returning id into target_id;
  insert into public.restaurant_staff(restaurant_id,user_id,role) values(target_id,auth.uid(),'owner');
  return jsonb_build_object('id',target_id,'slug',target_slug,'name',trim(p_name));
end;
$$;

create or replace function public.create_restaurant_tables(p_restaurant_id uuid,p_count integer)
returns integer language plpgsql security definer set search_path = public as $$
begin
  if not public.has_restaurant_role(p_restaurant_id,array['owner','manager']) then raise exception 'ACCESS_DENIED'; end if;
  if p_count not between 1 and 100 then raise exception 'TABLE_COUNT_OUT_OF_RANGE'; end if;
  insert into public.tables(restaurant_id,local_id,table_number,table_name,name,table_token,sort_order)
  select p_restaurant_id,'table-'||n,n,'Table '||n,'Table '||n,
    'tk_'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)),n
  from generate_series(1,p_count) n on conflict (restaurant_id,local_id) do nothing;
  return p_count;
end;
$$;

create or replace function public.get_public_restaurant(p_slug text,p_table_ref text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare result jsonb;
begin
  select jsonb_build_object(
    'restaurant',jsonb_build_object('id',r.id,'slug',r.slug,'name',r.name,'subtitle',r.subtitle,'address',r.address,
      'phone',r.phone,'tax_rate',r.tax_rate,'is_open',r.is_open,'logo_url',r.logo_url,'theme_config',r.theme_config,'timezone',r.timezone),
    'tables',(select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'local_id',t.local_id,'table_number',t.table_number,
      'table_name',t.table_name,'table_token',t.table_token,'sort_order',t.sort_order) order by t.sort_order),'[]'::jsonb)
      from public.tables t where t.restaurant_id=r.id and t.is_active and
        ((coalesce(p_table_ref,'')<>'' and (t.local_id=p_table_ref or t.table_token=p_table_ref)) or
         (coalesce(p_table_ref,'')='' and public.is_restaurant_staff(r.id)))),
    'menu_items',(select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'local_id',m.local_id,'category_id',m.category_id,
      'category',coalesce(c.name,m.category),'name',m.name,'description',m.description,'price',m.price,'tags',m.tags,
      'image_url',coalesce(nullif(m.image_url,''),m.photo_url),'option_template',m.option_template,
      'is_available',m.is_available and m.is_active and not m.sold_out,'sort_order',m.sort_order) order by c.sort_order,m.sort_order),'[]'::jsonb)
      from public.menu_items m left join public.categories c on c.id=m.category_id
      where m.restaurant_id=r.id and m.is_active and (c.is_active is null or c.is_active))
  ) into result from public.restaurants r
  where r.slug=p_slug and r.status in ('active','onboarding') and r.is_active;
  if result is null then raise exception 'RESTAURANT_NOT_FOUND'; end if;
  if coalesce(p_table_ref,'')<>'' and jsonb_array_length(result->'tables')<>1 then raise exception 'TABLE_NOT_FOUND'; end if;
  return result;
end;
$$;

create or replace function public.submit_order(
  p_restaurant_id uuid,p_table_id uuid,p_local_id text,p_note text,p_items jsonb,p_customer_name text default ''
) returns jsonb language plpgsql security definer set search_path = public as $$
declare target_order_id uuid; target_order_number bigint; target_tax_rate numeric(5,2);
  calculated_subtotal numeric(10,2); calculated_tax numeric(10,2); calculated_total numeric(10,2);
begin
  if length(trim(coalesce(p_local_id,'')))<3 then raise exception 'INVALID_ORDER_ID'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items) not between 1 and 50 then raise exception 'INVALID_ORDER_ITEMS'; end if;
  select r.tax_rate into target_tax_rate from public.restaurants r join public.tables t on t.restaurant_id=r.id
  where r.id=p_restaurant_id and r.status in ('active','onboarding') and r.is_open and t.id=p_table_id and t.is_active;
  if target_tax_rate is null then raise exception 'INVALID_OR_CLOSED_TABLE'; end if;
  select id,order_number into target_order_id,target_order_number from public.orders
    where restaurant_id=p_restaurant_id and local_id=p_local_id limit 1;
  if target_order_id is not null then return jsonb_build_object('id',target_order_id,'order_number',target_order_number); end if;
  if exists(select 1 from jsonb_array_elements(p_items) i where coalesce((i->>'quantity')::integer,0) not between 1 and 99
    or not exists(select 1 from public.menu_items m where m.id=nullif(i->>'menu_item_id','')::uuid
      and m.restaurant_id=p_restaurant_id and m.is_active and m.is_available and not m.sold_out)) then
    raise exception 'INVALID_ORDER_ITEM';
  end if;
  select round(sum(m.price*(i->>'quantity')::integer),2) into calculated_total
    from jsonb_array_elements(p_items) i join public.menu_items m on m.id=(i->>'menu_item_id')::uuid
    where m.restaurant_id=p_restaurant_id;
  calculated_tax:=round(calculated_total*target_tax_rate/(100+target_tax_rate),2);
  calculated_subtotal:=calculated_total-calculated_tax;
  insert into public.orders(restaurant_id,table_id,local_id,customer_name,status,note,subtotal,tax,total)
  values(p_restaurant_id,p_table_id,p_local_id,left(coalesce(p_customer_name,''),120),'new',left(coalesce(p_note,''),1000),calculated_subtotal,calculated_tax,calculated_total)
  returning id,order_number into target_order_id,target_order_number;
  insert into public.order_items(restaurant_id,order_id,menu_item_id,item_name,name_snapshot,quantity,price,base_price,unit_price,notes,options)
  select p_restaurant_id,target_order_id,m.id,m.name,m.name,(i->>'quantity')::integer,m.price,m.price,m.price,
    left(coalesce(i->>'notes',''),500),coalesce(i->'options','[]'::jsonb)
  from jsonb_array_elements(p_items) i join public.menu_items m on m.id=(i->>'menu_item_id')::uuid
  where m.restaurant_id=p_restaurant_id;
  return jsonb_build_object('id',target_order_id,'order_number',target_order_number);
end;
$$;

create or replace function public.get_customer_order_status(p_order_id uuid,p_local_id text,p_table_token text)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object('id',o.id,'local_id',o.local_id,'order_number',o.order_number,'status',o.status,
    'total',o.total,'created_at',o.created_at,'served_at',o.served_at,'closed_at',o.closed_at,
    'updated_at',o.updated_at,'table_name',t.table_name)
  from public.orders o join public.tables t on t.id=o.table_id and t.restaurant_id=o.restaurant_id
  where o.id=p_order_id and o.local_id=p_local_id and t.table_token=p_table_token and t.is_active
    and o.created_at>now()-interval '24 hours' limit 1;
$$;

revoke all on function public.create_restaurant_for_owner(text,text,text,text,text,text) from public;
revoke all on function public.create_restaurant_tables(uuid,integer) from public;
revoke all on function public.get_public_restaurant(text,text) from public;
revoke all on function public.submit_order(uuid,uuid,text,text,jsonb,text) from public;
revoke all on function public.get_customer_order_status(uuid,text,text) from public;
grant execute on function public.create_restaurant_for_owner(text,text,text,text,text,text),public.create_restaurant_tables(uuid,integer) to authenticated;
grant execute on function public.get_public_restaurant(text,text),public.submit_order(uuid,uuid,text,text,jsonb,text),
  public.get_customer_order_status(uuid,text,text) to anon,authenticated;

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
end;
$$;

notify pgrst,'reload schema';
